### ISSUE TITLE
No .passwd.h

### ISSUE THREAD

**Issue by GerryGit** [dirkx/SMPTE-EBU-TimecodeGenerator-ESP32#1]
Hi building in PlatformIO  throws an error: .passwd.h: No such file or directory.
This file and maybe a few others are not included in the zip.
Any assistance please.

**Comment by dirkx** [comment]
If you are in a rush - just remove that line and replace it by the lines:

	#define WIFI_NETWORK	"YourWifiNetwork"
	#define WIFI_PASSWD		"PasswordOfYourWifiNetwork"

with the right values. That wil make things work again. 

Dw.

**Comment by GerryGit** [comment]
Thanks for that. Builds now. Same in OTA.ino

**Comment by dirkx** [comment]
Gerry - see also last commit. This makes the NTP server config also visible.
