### ISSUE TITLE
Pin 12

### ISSUE THREAD

**Issue by VK2BEA** [dirkx/SMPTE-EBU-TimecodeGenerator-ESP32#13]
Should I see anything on pin 12?  It is permanently low and I do see Manchester code on pin 13.
I'm using the WROVER board.

**Comment by dirkx** [comment]
It is wired in https://github.com/dirkx/SMPTE-EBU-TimecodeGenerator-ESP32/blob/5f38098a2007c9abecf29c9db68a9010bea9a58e/SMPTEGenerator/ntp.ino#L127 — so it should be whatever RED_PIN is set to.

Note that you cannot easily measure this with a multimeter - as the format is designed to be balanced - and on average is always ‘half’. But a scope should show a pattern.

**Comment by VK2BEA** [comment]
No, I **do** see the SMPTE code on the 'red pin' (GPIO_NUM_13), it is the 'black pin' (GPIO_NUM_12) that I see 0V.
Is that right? I see it set low [here](https://github.com/dirkx/SMPTE-EBU-TimecodeGenerator-ESP32/blob/5f38098a2007c9abecf29c9db68a9010bea9a58e/SMPTEGenerator/SMPTEGenerator.ino#L79C3-L79C32) but not where it is changed. What is the point of wiring it to a pin if it is always low?
Also, what is the point of the SENSE_PIN input. I seems like it just alters the title on the web page.

BTW thanks for making this available ... its exactly what I was looking for!

**Comment by dirkx** [comment]
On 23 Oct 2024, at 23:32, Michael G. Katzmann ***@***.***> wrote:
> No, I do see the SMPTE code on the 'red pin' (GPIO_NUM_13), it is the 'black pin' (GPIO_NUM_12) that I see 0V.
> 
Ok - good and as expected. 
> Is that right? I see it set low here <https://github.com/dirkx/SMPTE-EBU-TimecodeGenerator-ESP32/blob/5f38098a2007c9abecf29c9db68a9010bea9a58e/SMPTEGenerator/SMPTEGenerator.ino#L79C3-L79C32> but not where it is changed. What is the point of wiring it to a pin if it is always low?
> 
There are some clocks that need an inverted input.
> Also, what is the point of the SENSE_PIN input. I seems like it just alters the title on the web page.
> 

Basically I have two types of clocks in common use - the analog one with a dial and digital ones. The sense pin lets me use the same firmwar/electronics on both - and it detects which type it is controlling.

Dw.

**Comment by VK2BEA** [comment]
> There are some clocks that need an inverted input.

I'm not seeing an inverted output on pin 12, it is always low.
I can see in the code [here](https://github.com/dirkx/SMPTE-EBU-TimecodeGenerator-ESP32/blob/5f38098a2007c9abecf29c9db68a9010bea9a58e/SMPTEGenerator/RMT.ino#L124) where you configure the 'red' output GPIO (13) but not where the 'black' GPIO (12) is set as an inverted version.

**Comment by dirkx** [comment]
On 24 Oct 2024, at 13:39, Michael G. Katzmann ***@***.***> wrote:
> There are some clocks that need an inverted input.
> 
> I'm not seeing an inverted output on pin 12, it is always low.
> I can see in the code here <https://github.com/dirkx/SMPTE-EBU-TimecodeGenerator-ESP32/blob/5f38098a2007c9abecf29c9db68a9010bea9a58e/SMPTEGenerator/RMT.ino#L124> where you configure the 'red' output GPIO (13) but not where the 'black' GPIO (12) is set as an inverted version.
> 

Simply set it to high rather than low or vise versa if your clock needs that.

**Comment by VK2BEA** [comment]
> Simply set it to high rather than low or vise versa if your clock needs that.

OK, I see now what you meant. Thanks, it looks like my ESP32 board is executing the program normally.

_BTW you have a typo [here](https://github.com/dirkx/SMPTE-EBU-TimecodeGenerator-ESP32/blob/5f38098a2007c9abecf29c9db68a9010bea9a58e/SMPTEGenerator/WebConfig.ino#L53) (ublications rather than publications)_

**Comment by dirkx** [comment]
Patches/pull requests for a nicer interface always appreciated.

**Comment by dirkx** [comment]
issue/question anserwed/resolved.
