### ISSUE TITLE
Transistor driver unnecessary for some clocks

### ISSUE THREAD

**Issue by mikemccauley** [dirkx/SMPTE-EBU-TimecodeGenerator-ESP32#9]
Documentation of this excellent program indicates the need for a transistor driver to convert the 3.3 V output from the ESP32 to 5V for the clock.

Reading the documentation for my Leitch ADC-5100 cloks shows that the required SMPTE input is 

4 V p-p +/- 8 dB
balanced

which 3.3 V is well within.
I connect the black wire of the clock to the ESP32 ground and the red wire to the ESP32 SMPTE output and have no problems. Probing the signal conditioning of the clock shows a clean signal SMPTE into the CPU.

So perhaps the transistor driver is not necessary, at least for some?

**Comment by philpem** [comment]
I have a Gorgy SMPTE-input clock; the input stage expects a capacitively-coupled input. If the timecode input doesn't go below ground, it won't detect the encoded bits correctly.

It's possibly worth noting that some clocks behave like that -- and a 10uF series capacitor is all that's needed to get them working, no transistor.

At the end of the day it's going to depend on the input stage in the clock, and clearly there's some variation there.

**Comment by dirkx** [comment]
added to Readme.
